name: Heartbeat

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL'
        required: true
        type: string

jobs:
  twitter:
    name: Heartbeat twitter.com
    runs-on: ubuntu-latest
    steps:
      - name: get twitter.com http status code
        id: http-code
        run: |
          echo "HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' ${{ inputs.target_url }})" >> $GITHUB_OUTPUT
      - name: check twitter.com http status code
        run: |
          if [[ "${{ steps.http-code.outputs.HTTP_CODE }}" -ge 400 ]]; then
            exit 1
          fi
